### ISSUE TITLE
API URL not coming up 

### ISSUE THREAD

**Issue by ciarapowell** [UF-COP5035/Rater-System#92]
When I type http://localhost:3000/api/courses I get the error:

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:81:11)
    at Object.urlParse [as parse] (url.js:75:5)
    at module.exports (C:\Users\Ciara\Code\Rater-System\node_modules\mongodb\lib\url_parser.js:16:23)
    at connect (C:\Users\Ciara\Code\Rater-System\node_modules\mongodb\lib\mongo_client.js:486:16)
    at Function.MongoClient.connect (C:\Users\Ciara\Code\Rater-System\node_modules\mongodb\lib\mongo_client.js:250:3)
    at connection (C:\Users\Ciara\Code\Rater-System\server\routes\api.js:14:24)
    at router.get (C:\Users\Ciara\Code\Rater-System\server\routes\api.js:698:5)
    at Layer.handle [as handle_request] (C:\Users\Ciara\Code\Rater-System\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Ciara\Code\Rater-System\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Ciara\Code\Rater-System\node_modules\express\lib\router\route.js:112:3)

Should I be able to enter this url to get the api results?
I am doing this to confirm db connection for api calls in ts file.  
I have the env file in my project.

**Comment by ciarapowell** [comment]
@ltcarbonell @christopher1030123 : Any Insights? 

Thanks

**Comment by ltcarbonell** [comment]
Yeah you should be able to just type /api/courses. I will look into it.

**Comment by ltcarbonell** [comment]
I'm not getting any errors on my end. I am able to get the courses from localhost:3000/api/courses

**Comment by ltcarbonell** [comment]
Closing as question answered

**Comment by ciarapowell** [comment]
Would you know why it is giving this error? Me and @rahulp94 are seeing it and it is preventing me from actually testing the api calls. I am getting errors when it is passed.

**Comment by christopher1030123** [comment]
Actually I am not seeing it
